name = "cf-proxy-mysql"
main = "src/index.js"
compatibility_date = "2026-08-18"
compatibility_flags = ["nodejs_compat"]

[vars]
# 你的后台管理员密码
ADMIN_PASS = "admin"

# 绑定你的 Hyperdrive
[[hyperdrive]]
binding = "HYPERDRIVE"
id = "73d601307e2d4dfd9837de568bfacba8"
